<?php
require_once __DIR__ . '/_require_admin.php';

// Very simple HTML-to-PDF fallback: for now, returns HTML with headers so user can print to PDF.
// You can later swap to dompdf/tcpdf.

try {
    $id = (int)($_GET['id'] ?? 0);
    if ($id <= 0) throw new Exception('id required');
    $stmt = $pdo->prepare('SELECT i.id, i.created_at AS invoice_date, i.total, i.paid, i.status, i.notes, p.first_name, p.last_name
                           FROM invoices i JOIN patients p ON i.patient_id = p.id WHERE i.id = :id');
    $stmt->execute([':id'=>$id]);
    $inv = $stmt->fetch(PDO::FETCH_ASSOC);
    if (!$inv) throw new Exception('not found');

    // HTML output (reliable in XAMPP without PDF libs). Use browser Print → Save as PDF.
    header('Content-Type: text/html; charset=utf-8');
    header('Content-Disposition: inline; filename="invoice-'.$id.'.html"');
    echo '<!doctype html><html><head><meta charset="utf-8"><title>Invoice #'.$id.'</title>';
    echo '<style>body{font-family:Arial;padding:24px} .hdr{display:flex;justify-content:space-between;margin-bottom:12px} table{width:100%;border-collapse:collapse} td,th{border:1px solid #ddd;padding:8px}</style>';
    echo '</head><body>';
    echo '<div class="hdr"><h2>Invoice #'.$id.'</h2><div>'.htmlspecialchars($inv['invoice_date']).'</div></div>';
    echo '<p><strong>Patient:</strong> '.htmlspecialchars(($inv['first_name']??'').' '.($inv['last_name']??'')).'</p>';
    echo '<table><tr><th>Total</th><th>Paid</th><th>Status</th></tr><tr><td>'.htmlspecialchars($inv['total']).'</td><td>'.htmlspecialchars($inv['paid']).'</td><td>'.htmlspecialchars($inv['status']).'</td></tr></table>';
    if (!empty($inv['notes'])) echo '<p><strong>Notes:</strong> '.htmlspecialchars($inv['notes']).'</p>';
    echo '<p style="margin-top:40px;font-size:12px;color:#666">Generated by Golden Oak</p>';
    echo '</body></html>';
} catch (Throwable $e) {
    http_response_code(400);
    echo 'Error: ' . htmlspecialchars($e->getMessage());
}


