<?php
require_once __DIR__ . '/../includes/fpdf185/fpdf.php';
require_once __DIR__ . '/db.php';

// Prevent unwanted output before PDF
error_reporting(E_ERROR | E_PARSE);
ob_clean();

// Fetch all lab cases
$stmt = $pdo->query("SELECT l.*, p.first_name, p.last_name 
                     FROM lab_cases l 
                     LEFT JOIN patients p ON l.patient_id = p.id 
                     ORDER BY l.created_at DESC");
$cases = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// === HEADER WITH LOGO ===
$logoPath = "E:/DENTAL CLINIC/images/logo-removebg-preview.png"; 
if (file_exists($logoPath)) {
    $pdf->Image($logoPath, 10, 8, 25);
}

$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 10, 'GOLDENT OAK DENTAL CARE', 0, 1, 'C');
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'All Lab Cases Report', 0, 1, 'C');
$pdf->Ln(10);

// === TABLE HEADER ===
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(10, 10, '#', 1);
$pdf->Cell(45, 10, 'Patient', 1);
$pdf->Cell(70, 10, 'Description', 1);
$pdf->Cell(25, 10, 'Status', 1);
$pdf->Cell(40, 10, 'Created', 1);
$pdf->Ln();

// === TABLE CONTENT ===
$pdf->SetFont('Arial', '', 11);

function convertText($text) {
    return mb_convert_encoding($text ?? '', 'ISO-8859-1', 'UTF-8');
}

$counter = 1;
foreach ($cases as $case) {
    $pdf->Cell(10, 10, $counter++, 1);

    // Patient name
    $patient = convertText(($case['first_name'] ?? '') . ' ' . ($case['last_name'] ?? ''));
    $pdf->Cell(45, 10, $patient, 1);

    // Description (shortened if too long)
    $desc = convertText(substr($case['description'] ?? '', 0, 35));
    $pdf->Cell(70, 10, $desc, 1);

    // Status
    $pdf->Cell(25, 10, convertText($case['status'] ?? ''), 1);

    // Format date
    $createdDate = '';
    if (!empty($case['created_at'])) {
        $createdDate = date('M d, Y', strtotime($case['created_at']));
    }
    $pdf->Cell(40, 10, convertText($createdDate), 1);
    $pdf->Ln();
}

// === FOOTER ===
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(0, 10, 'Generated by Goldent Oak Dental Care System', 0, 0, 'C');

// === OUTPUT PDF ===
$pdf->Output('D', 'lab_cases_report.pdf');
exit;
?>
