<?php
require_once __DIR__ . '/../includes/fpdf185/fpdf.php';
require_once __DIR__ . '/db.php';

// Prevent unwanted output before PDF
error_reporting(E_ERROR | E_PARSE);
ob_clean();

$id = $_GET['id'] ?? 0;
$stmt = $pdo->prepare("SELECT l.*, p.first_name, p.last_name 
                       FROM lab_cases l 
                       LEFT JOIN patients p ON l.patient_id = p.id 
                       WHERE l.id = ?");
$stmt->execute([$id]);
$case = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$case) {
    die("Lab case not found.");
}

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// === HEADER WITH LOGO ===
$logoPath = "E:/DENTAL CLINIC/images/logo-removebg-preview.png"; // your logo path
if (file_exists($logoPath)) {
    $pdf->Image($logoPath, 10, 8, 25); // (path, x, y, width)
}

$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 10, 'GOLDENT OAK DENTAL CARE', 0, 1, 'C');
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Lab Case Details', 0, 1, 'C');
$pdf->Ln(10);

// === BODY CONTENT ===
$pdf->SetFont('Arial', '', 12);

function convertText($text) {
    return mb_convert_encoding($text ?? '', 'ISO-8859-1', 'UTF-8');
}

$pdf->Cell(50, 10, 'Patient:', 0);
$pdf->Cell(0, 10, convertText(($case['first_name'] ?? '') . ' ' . ($case['last_name'] ?? '')), 0, 1);

$pdf->Cell(50, 10, 'Description:', 0);
$pdf->MultiCell(0, 10, convertText($case['description'] ?? ''));

$pdf->Cell(50, 10, 'Status:', 0);
$pdf->Cell(0, 10, convertText($case['status'] ?? ''), 0, 1);

// ✅ Format "Created At" into a readable date format
$pdf->Cell(50, 10, 'Created At:', 0);
$formattedDate = '';
if (!empty($case['created_at'])) {
    $formattedDate = date('M d, Y', strtotime($case['created_at'])); // e.g., Oct 14, 2025
}
$pdf->Cell(0, 10, convertText($formattedDate), 0, 1);

// === FOOTER ===
$pdf->Ln(20);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(0, 10, 'Generated by Goldent Oak Dental Care System', 0, 0, 'C');

// Output PDF
$pdf->Output('D', 'lab_case_' . $id . '.pdf');
exit;
?>
